name: CD
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - docs

jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            https://api.github.com/repos/${{ secrets.BUILDER }}/dispatches \
            -d '{"event_type":"deploy", "client_payload":{"branch": "${{ github.ref_name }}"}}'
