name: check
on:
  push:
    branches:
      - main
      - master
      - develop
      - 'feature/**'
env:
  PROJECT_NAME: psyki-python
  WORKFLOW: check
jobs:
  run-unit-tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          - '3.9.0'
          - '3.9.10'
          - '3.9.13'
    runs-on: ${{ matrix.os }}
    name: Run tests on Python ${{ matrix.python-version }}, on ${{ matrix.os }}
    timeout-minutes: 45
    concurrency:
      group: ${{ github.workflow }}-run-unit-tests-${{ matrix.python-version }}-${{ matrix.os }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate Datalog parser
        run: python setup.py generate_antlr4_parser

      - name: Download dataset for test in Windows
        if: ${{ matrix.os }} == 'windows-latest'
        run: |
          curl -o test/resources/data/poker/test.csv --url https://archive.ics.uci.edu/ml/machine-learning-databases/poker/poker-hand-testing.data
          curl -o test/resources/data/poker/train.csv --url https://archive.ics.uci.edu/ml/machine-learning-databases/poker/poker-hand-training-true.data

      - name: Download dataset for test no windows
        if: ${{ matrix.os }} != 'windows-latest'
        run: |
          wget https://archive.ics.uci.edu/ml/machine-learning-databases/poker/poker-hand-testing.data -O test/resources/data/poker/test.csv
          wget https://archive.ics.uci.edu/ml/machine-learning-databases/poker/poker-hand-training-true.data -O test/resources/data/poker/train.csv

      - name: Test
        run: python -m unittest discover -s test -t .