name: check
on:
  push:
    branches:
      - main
      - master
      - develop
      - 'feature/**'
env:
  PROJECT_NAME: psyki-python
  WORKFLOW: check
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.9.0'
          - '3.9.1'
          - '3.9.2'
          - '3.9.3'
          - '3.9.4'
          - '3.9.5'
          - '3.9.6'
          - '3.9.7'
    name: Run tests on Python ${{ matrix.python-version }}
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore Python dependencies
        run: |
          pip install -r requirements.txt
          conda install cudatoolkit

      - name: Generate Datalog parser
        run: |
          wget https://www.antlr.org/download/antlr-4.9.2-complete.jar
          export CLASSPATH="./antlr-4.9.2-complete.jar:$CLASSPATH"
          java -jar ./antlr-4.9.2-complete.jar -Dlanguage=Python3 resources/Datalog.g4 -visitor -o resources/dist

      - name: Download dataset for test
        run: |
          wget https://archive.ics.uci.edu/ml/machine-learning-databases/poker/poker-hand-testing.data -O test/resources/data/poker/test.csv
          wget https://archive.ics.uci.edu/ml/machine-learning-databases/poker/poker-hand-training-true.data -O test/resources/data/poker/train.csv

      - name: Test
        run: python -m unittest