name: check
on:
  push:
    branches:
      - main
      - master
      - develop
      - 'feature/**'
env:
  PROJECT_NAME: psyki-python
  WORKFLOW: check
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.9.0'
          - '3.9.1'
          - '3.9.2'
          - '3.9.3'
          - '3.9.4'
          - '3.9.5'
          - '3.9.6'
          - '3.9.7'
    name: Run tests on Python ${{ matrix.python-version }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore Python dependencies
        run: pip install -r requirements.txt

      - name: Test
        run: python -m unittest